### ISSUE TITLE
No documentation for implementation with Hardhat

### ISSUE THREAD

**Issue by wei3erHase** [nachomazzara/eth-block-timestamp#17]
I'm failing to find how to implement this repo with Hardhat and Ethers. 
```
const blocks = new Blocks(
  (window as any).ethereum || 'https://mainnet.infura.io/v3/{API_KEY}'
)
```
How should I initialize Blocks?

**Comment by nachomazzara** [comment]
are you seeing any error?

**Comment by wei3erHase** [comment]
it just answers a Null value when used

**Comment by nachomazzara** [comment]
What are you passing to `new Blocks()`? it should be a provider or RPC URL

**Comment by wei3erHase** [comment]
`import { ethers, network } from 'hardhat';`
`const blocks = new Blocks( network.provider )`
should this work?

**Comment by nachomazzara** [comment]
never try with ethers or hardhat :( Will need to take a look. You get `null` by using it? Can you try using just the rpc URL? 

For hardhat I guess that is `localhost:8545`

**Comment by wei3erHase** [comment]
```
TSError: ⨯ Unable to compile TypeScript:
test/e2e/event-fetcher.spec.ts:181:8 - error TS2339: Property 'block' does not exist on type 'BlockResponse | null'.

181     ({ block,  } = await blocks.getDate('2021-07-01'))
           ~~~~~
```

**Comment by wei3erHase** [comment]
```
TSError: ⨯ Unable to compile TypeScript:
test/e2e/event-fetcher.spec.ts:181:13 - error TS2531: Object is possibly 'null'.

181     block = (await blocks.getDate('2021-07-01')).block
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by nachomazzara** [comment]
Can you console the result of `(await blocks.getDate('2021-07-01'))` ? how are you initializing `Blocks` no?

**Comment by wei3erHase** [comment]
i'm initializing directly with alchemy api URL

i guess is just an error with typescript, when i do `console.log(await blocks.getDate('03/20/2020'))` it answers correctly:
`{ timestamp: 1584658800, block: 9704923 }`

it even understands yyyy-mm-dd (thanks for that):
`console.log(await blocks.getDate('2021-07-01'))`
`{ timestamp: 1625097600, block: 12738509 }`

but typescript asumes it may come as null so it's not able to compile

will keep posted, thanks!

**Comment by nachomazzara** [comment]
you can use:

```ts
data = (await blocks.getDate('2021-07-01'))
if (data) {
  // use data.block & data.timestamp
}```

Will update the Docs

**Comment by wei3erHase** [comment]
Will try, thank you very much champ! 🇦🇷
